I'm sorry, but an uncaught exception occurred.

While loading <renpy.display.im.Image object ('true_port2.png') at 0x00000000052493a0>:
  File "game/script.rpy", line 25, in script
    "Presiona [espacio] para continuar"
NameError: name 'espacio' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 25, in script
    "Presiona [espacio] para continuar"
  File "C:\Users\NovaroTp\Desktop\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "C:\Users\NovaroTp\Desktop\renpy-8.3.7-sdk\renpy\ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\NovaroTp\Desktop\renpy-8.3.7-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "C:\Users\NovaroTp\Desktop\renpy-8.3.7-sdk\renpy\character.py", line 1456, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "C:\Users\NovaroTp\Desktop\renpy-8.3.7-sdk\renpy\character.py", line 1369, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\NovaroTp\Desktop\renpy-8.3.7-sdk\renpy\character.py", line 1349, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\NovaroTp\Desktop\renpy-8.3.7-sdk\renpy\substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "C:\Users\NovaroTp\Desktop\renpy-8.3.7-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "C:\Users\NovaroTp\Desktop\renpy-8.3.7-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "C:\Users\NovaroTp\Desktop\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\NovaroTp\Desktop\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'espacio' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.7.25031702
Contaminacion 1.0
Sun Jun 22 19:12:17 2025
